### ISSUE TITLE
lru_cache TypeError

### ISSUE THREAD

**Issue by vonsago** [TimothyHTimothy/FAST-VQA#25]
I run FAST-VQA.ipynb In[1], but get this error:
```
>>> from fastvqa.apis import deep_end_to_end_vqa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/FAST-VQA-and-FasterVQA/fastvqa/__init__.py", line 1, in <module>
    from .datasets import *
  File "/app/FAST-VQA-and-FasterVQA/fastvqa/datasets/__init__.py", line 15, in <module>
    from .fusion_datasets import get_spatial_fragments, SimpleDataset, FusionDataset,  LSVQPatchDataset, FusionDatasetK400
  File "/app/FAST-VQA-and-FasterVQA/fastvqa/datasets/fusion_datasets.py", line 130, in <module>
    def get_resize_function(size_h, size_w, target_ratio=1, random_crop=False):
  File "/usr/local/lib/python3.7/functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
```
and  FAST-VQA.ipynb need to update.

**Comment by vonsago** [comment]
my fault, py3.8 is needed
