### ISSUE TITLE
andb.errors.UsageError: api_key not configured

### ISSUE THREAD

**Issue by SajjadHaydar** [TimothyHTimothy/FAST-VQA#44]
I am trying to train with the given command: python new_train.py -o options/fast/fast-b.yml
but I am getting this error:
Traceback (most recent call last):
  File "/proj/noref-videomodel/FAST-VQA-and-FasterVQA/new_train.py", line 617, in <module>
    main()
  File "/proj/noref-videomodel/FAST-VQA-and-FasterVQA/new_train.py", line 394, in main
    run = wandb.init(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1195, in init
    raise e
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1172, in init
    wi.setup(kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 306, in setup
    wandb_login._login(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 317, in _login
    wlogin.prompt_api_key()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 247, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])

Do we need wandb API's key? If, yes, then how to get it for this project?

**Comment by Hellopass** [comment]
I also encountered this issue, and here's how I solved it:

1. Run `pip install wandb`.
2. [to wandb.ai](https://wandb.ai/site), click "Settings" in the top right corner, and you will see the API key.
3. Enter `wandb login` in the terminal, then input the API key.
